base_url = "https://github.io"
title = "My Ametrine Site"
theme = "ametrine"

compile_sass = true
build_search_index = true

[markdown]

[markdown.highlighting]
theme = "github-dark"

[extra]
# Providing these standard definitions prevents the theme from hitting empty/null variable bugs
author = "kakalot17"
description = "A clean personal site built with Zola and Ametrine."
avatar = ""
